### ISSUE TITLE
Als student wil ik mijn nog in te vullen formulieren kunnen inzien

### ISSUE THREAD

**Issue by RemcoKok** [RemcoKok/Skills-Monitor#25]
- [ ] De student moet naar een nieuwe pagina kunnen navigeren/
- [ ] Op de pagina moet een grafiek te zie zijn met het aantal lege formulieren.
- [ ] Op de pagina moeten alle lege formulieren worden weergegeven.
- [ ] De formulieren moeten onder een "onderwerp" komen te staan.
- [ ] De student moet de formulieren kunnen inzien door er op te klikken.
- [ ] De student moet op formulier invullen kunnen klikken vanuit het scherm waar hij of zij het formulier kan inzien.
- [ ] Er moet een connectie zijn met de database.

**Comment by M4RNIX** [comment]
- [ ] Hoi
- [ ] Doei
